quarkus.openapi-generator.codegen.spec.openapi_yml.model-name-prefix=QuarkusOpenApiGenerator

quarkus.datasource.db-kind=postgresql 
quarkus.datasource.username=<your username>
quarkus.datasource.password=<your password>

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hibernate_orm_test
quarkus.datasource.jdbc.max-size=16

# Trocar para update quando quiser atualizar as tabelas do banco de dados
# CAREFUL: utilizar com cuidado
quarkus.hibernate-orm.database.generation=none