quarkus.openapi-generator.codegen.spec.openapi_yml.model-name-prefix=QuarkusOpenApiGenerator
quarkus.application.name=qdule-backend

quarkus.datasource.db-kind=postgresql 
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASS}

quarkus.datasource.jdbc.url=${JDBC_URL}
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.database.generation=none

quarkus.swagger-ui.path=/api
quarkus.smallrye-openapi.path=/openapi
quarkus.http.root-path=/

quarkus.micrometer.export.prometheus.enabled=true
quarkus.otel.enabled=${OTEL_ENABLED:false}
quarkus.otel.service.name=qdule-backend
quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}

%dev.quarkus.otel.enabled=true
%dev.quarkus.observability.lgtm.grafana-port=3001
%dev.quarkus.observability.lgtm.otel-grpc-port=5317
%dev.quarkus.observability.lgtm.otel-http-port=5318

resend.api-key=${RESEND_APIKEY}

smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=qdule

quarkus.http.cors.enabled=true
