quarkus.openapi-generator.codegen.spec.openapi_yml.model-name-prefix=QuarkusOpenApiGenerator

quarkus.datasource.db-kind=database
quarkus.datasource.username=username
quarkus.datasource.password=password

quarkus.datasource.jdbc.url=url
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.database.generation=none
